#!/usr/bin/python

import sys
import I2C_LCD_driver
from pad4pi import rpi_gpio
import time

mylcd = I2C_LCD_driver.lcd()

#!/usr/bin/python

MATRIX = [['1','2','3','A'],
          ['4','5','6','B'],
          ['7','8','9','C'],
          ['*','0','#','D']]

#BCM numbering
COLS = [4,17,27,22]
ROWS = [6,13,19,26]

factory = rpi_gpio.KeypadFactory()
keypad = factory.create_keypad(keypad=MATRIX, row_pins=ROWS, col_pins=COLS)

freq = "120.0000"
midx = 0
modes = ["NFM", "WFM", "AM ", "LSB", USB"]



def updateLcd():
	global mylcd
	global freq
	global mode

	freq = freq[:10]

	mylcd.lcd_display_string(freq, 1, 0)
	mylcd.lcd_display_string("Mhz", 1, 13)
	mylcd.lcd_display_string(mode, 2, 0)
	

def printKey(key):
	global lcd1
	global lcd2
	global mylcd

	if key == "#":
		mylcd.lcd_clear()
		lcd1 = lcd1[:len(lcd1) - 1]
	elif key == "*":
		lcd1 = lcd1 + "."
	elif key == "A":
		freq = int(
	elif key == "B":
		if lcd2 == "NFM":
			lcd2 = "WFM"
		elif lcd2 == "WFM":
			lcd2 = "AM "
		elif lcd2 == "AM ":
			lcd2 = "LSB"
		elif lcd2 == "LSB":
			lcd2 = "USB"
		elif lcd2 == "USB":
			lcd2 = "NFM"
	else:
		lcd1 = lcd1 + key

	mylcd.lcd_display_string(lcd1, 1)
	mylcd.lcd_display_string(lcd2, 2)


keypad.registerKeyPressHandler(printKey)

try:
	while(True):
		#print("keypad: sleeping...")
		time.sleep(0.2)
except:
	#print("keypad: cleaning up")
	keypad.cleanup()

